Import libraries

In [182]:
import pandas as pd
import numpy as np

In [148]:
output=pd.read_excel("/content/Sample Output.xlsx")

In [149]:
input1=pd.read_excel("/content/Sample Input1 - Sample.xlsx")

In [150]:
input2=pd.read_excel("/content/Sample Input2 - Sample.xlsx")

In [ ]:
input1.head(2)

,ItemId,ComputerId,ItemName,Comment,Unit,C/S/ID,DataType,BitPos,Address,MAX,MIN,ScaleMax,ScaleMin,Decimal
0,35827,10,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),NaN,0,REAL : Float,0,0x16464,10000.0,-10000.0,10000.0,-10000.0,0.0
1,35828,10,L_R1SDD_SPDREF,R1 Screw Down DS Speed Reference (mps),NaN,0,REAL : Float,0,0x16468,10000.0,-10000.0,10000.0,-10000.0,0.0

In [ ]:
input2.head(2)

,Date,Time,Milli Sec,L_R1SDW_SPDREF,L_R1SDD_SPDREF,L_R1SDL_SPDREF,L_R1SDW_SPDFBK,L_R1SDD_SPDFBK,L_R1SDL_SPDFBK,L_R1_ODG_AUX_B07,...,L_R1SD_DS_GAP,L_R1SD_WS_SPDREF,L_R1SD_DS_SPDREF,L_R1SDLS_SPDREF,L_R1SD_WS_SPDFBK,L_R1SD_DS_SPDFBK,L_R1SDLS_SPDFBK,L_R1SD_WS_CUR,L_R1SD_DS_CUR,L_R1_CNT_PASS0
0,2022-06-05,21:58:33,140,0.0,0.0,0,0.0,0.0,0,0,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1
1,2022-06-05,21:58:33,145,0.0,0.0,0,0.0,0.0,0,0,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1

In [ ]:
output.head(1)

,event_timestamp,tag__id,tag__name,tag__desc,tag__value,tag__unit
0,2021-08-05 21:30:39,35827.0,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),0.0,mps

In [183]:
df1 = input1[['ItemId','ItemName','Comment']]

In [ ]:
df1.head(1)

   ItemId        ItemName                                 Comment
0   35827  L_R1SDW_SPDREF  R1 Screw Down WS Speed Reference (mps)

In [184]:
df2=input2.drop(['Milli Sec'],axis=1)

In [ ]:
df2.head(5)

,Date,Time,L_R1SDW_SPDREF,L_R1SDD_SPDREF,L_R1SDL_SPDREF,L_R1SDW_SPDFBK,L_R1SDD_SPDFBK,L_R1SDL_SPDFBK,L_R1_ODG_AUX_B07,RM1_RUNDOWN_ID_HS,...,L_R1SD_DS_GAP,L_R1SD_WS_SPDREF,L_R1SD_DS_SPDREF,L_R1SDLS_SPDREF,L_R1SD_WS_SPDFBK,L_R1SD_DS_SPDFBK,L_R1SDLS_SPDFBK,L_R1SD_WS_CUR,L_R1SD_DS_CUR,L_R1_CNT_PASS0
0,2022-06-05,21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1
1,2022-06-05,21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1
2,2022-06-05,21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1
3,2022-06-05,21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1
4,2022-06-05,21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,...,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1

In [185]:
df2.insert(2, "Time_Stamp", df2['Date'].astype(str) +" "+ df2["Time"].astype(str), True)

In [186]:
df2=df2.drop(columns=['Date','Time'],axis=1)

In [ ]:
df2.head(2)

,Time_Stamp,L_R1SDW_SPDREF,L_R1SDD_SPDREF,L_R1SDL_SPDREF,L_R1SDW_SPDFBK,L_R1SDD_SPDFBK,L_R1SDL_SPDFBK,L_R1_ODG_AUX_B07,RM1_RUNDOWN_ID_HS,L_R1SD_WS_GAP,L_R1SD_DS_GAP,L_R1SD_WS_SPDREF,L_R1SD_DS_SPDREF,L_R1SDLS_SPDREF,L_R1SD_WS_SPDFBK,L_R1SD_DS_SPDFBK,L_R1SDLS_SPDFBK,L_R1SD_WS_CUR,L_R1SD_DS_CUR,L_R1_CNT_PASS0
0,2022-06-05 21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,194.430008,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1
1,2022-06-05 21:58:33,0.0,0.0,0,0.0,0.0,0,0,225726050,194.430008,194.347992,0.0,0.0,0,0.0,0.0,0,0,0,1

In [187]:
df2['Time_Stamp'] = pd.to_datetime(df2['Time_Stamp'], errors='coerce')

In [198]:
df5=df2.groupby(pd.Grouper(key='Time_Stamp', freq='10s')).max()

In [201]:
df5.head(1)

,L_R1SDW_SPDREF,L_R1SDD_SPDREF,L_R1SDL_SPDREF,L_R1SDW_SPDFBK,L_R1SDD_SPDFBK,L_R1SDL_SPDFBK,L_R1_ODG_AUX_B07,RM1_RUNDOWN_ID_HS,L_R1SD_WS_GAP,L_R1SD_DS_GAP,L_R1SD_WS_SPDREF,L_R1SD_DS_SPDREF,L_R1SDLS_SPDREF,L_R1SD_WS_SPDFBK,L_R1SD_DS_SPDFBK,L_R1SDLS_SPDFBK,L_R1SD_WS_CUR,L_R1SD_DS_CUR,L_R1_CNT_PASS0
Time_Stamp,,,,,,,,,,,,,,,,,,,
2022-06-05 21:58:30,0.0,0.0,0,0.0,0.0,0,1,225726050,194.680008,194.619995,0.0,0.0,0,0.0,0.0,0,0,0,1

In [202]:
Tag_values=[]
Time_Stamp=[]
for i in df1['ItemName']:
  for j in df5.columns:
    if i==j:
      Tag_values.append(max(df5[i]))
      Time_Stamp.append(df5[j])

In [159]:
df1['Tag_values']=Tag_values
df1['Event_Time_stamp']=Time_Stamp

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [161]:
df1['Tag_ID']=df1['ItemId']
df1['Tag_Name']=df1['ItemName']
df1['tag__desc']=df1['Comment']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [163]:
df1.head(1)

,ItemId,ItemName,Comment,Tag_values,Event_Time_stamp,Tag_ID,Tag_Name,tag__desc
0,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),29.866667,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps)

In [164]:
df1=df1.drop(columns=['ItemId','ItemName','Comment'])

In [171]:
df1['Unit']=df1['tag__desc'].str.extract(r'\((\w+)\)', expand=True)

In [172]:
df1.head(1)

,Tag_values,Event_Time_stamp,Tag_ID,Tag_Name,tag__desc,Unit
0,29.866667,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),mps

In [177]:
df1=df1[['Event_Time_stamp','Tag_ID','Tag_Name','tag__desc','Tag_values','Unit']]

In [178]:
df1

,Event_Time_stamp,Tag_ID,Tag_Name,tag__desc,Tag_values,Unit
0,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),2.986667e+01,mps
1,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,35828,L_R1SDD_SPDREF,R1 Screw Down DS Speed Reference (mps),2.986667e+01,mps
2,Time_Stamp 2022-06-05 21:58:30 0 2022-06-05...,35829,L_R1SDL_SPDREF,R1 Screw Down LS Speed Reference (mps),0.000000e+00,mps
3,Time_Stamp 2022-06-05 21:58:30 0.0000 2022...,35830,L_R1SDW_SPDFBK,R1 Screw Down WS Speed Feedback (mps),1.678240e+01,mps
4,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,35831,L_R1SDD_SPDFBK,R1 Screw Down DS Speed Feedback (mps),1.681280e+01,mps
5,Time_Stamp 2022-06-05 21:58:30 0 2022-06-05...,35832,L_R1SDL_SPDFBK,R1 Screw Down LS Speed Feedback (mps),0.000000e+00,mps
6,Time_Stamp 2022-06-05 21:58:30 1 2022-06-05...,35974,L_R1_ODG_AUX_B07,R1 ODG AUX output B07,1.000000e+00,NaN
7,Time_Stamp 2022-06-05 21:58:30 225726050 20...,83528,RM1_RUNDOWN_ID_HS,R! RUNDOWN ID,2.257260e+08,NaN
8,Time_Stamp 2022-06-05 21:58:30 194.680008 2...,83530,L_R1SD_WS_GAP,R1 SCREW DOWN WORK SIDE GAP (MM),1.946800e+02,MM
9,Time_Stamp 2022-06-05 21:58:30 194.619995 2...,83531,L_R1SD_DS_GAP,R1 SCREW DOWN DRIVE SIDE GAP (MM),1.946200e+02,MM
10,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,83532,L_R1SD_WS_SPDREF,R1 SCREW DOWN WS SPD REF (MPS),2.986667e+01,MPS
11,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,83533,L_R1SD_DS_SPDREF,R1 SCREW DOWN DS SPD REF (MPS),2.986667e+01,MPS
12,Time_Stamp 2022-06-05 21:58:30 0 2022-06-05...,83534,L_R1SDLS_SPDREF,R1 SCREW DOWN LOW SPEED REF (MPS),0.000000e+00,MPS
13,Time_Stamp 2022-06-05 21:58:30 0.0000 2022...,83535,L_R1SD_WS_SPDFBK,R1 SCREW DOWN WS SPEED FBK (MPS),1.678240e+01,MPS
14,Time_Stamp 2022-06-05 21:58:30 0.000000 20...,83536,L_R1SD_DS_SPDFBK,R1 SCREW DOWN DS SPEED FBK (MPS),1.681280e+01,MPS
15,Time_Stamp 2022-06-05 21:58:30 0 2022-06-05...,83537,L_R1SDLS_SPDFBK,R1 SCREW DOWN LS SPEED FBK (MPS),0.000000e+00,MPS
16,Time_Stamp 2022-06-05 21:58:30 0 2022-06-...,83538,L_R1SD_WS_CUR,R1 SCREW DOWN WS CURRENT (%),1.890000e+02,NaN
17,Time_Stamp 2022-06-05 21:58:30 0 2022-06-...,83539,L_R1SD_DS_CUR,R1 SCREW DOWN DS CURRENT (%),2.130000e+02,NaN
18,Time_Stamp 2022-06-05 21:58:30 1 2022-06-05...,83540,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,1.000000e+00,NaN

In [203]:
df1.to_csv("output.csv")